spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
  datasource:
    url: jdbc:h2:mem:book_store_db;MODE=MYSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQL5Dialect

springdoc:
  version: 1.0.0
  swagger-ui:
    enabled: true
    operationsSorter: method
  api-docs:
    enabled: true


server:
  port: 9999
  servlet:
    context-path: /book-store-service
