name: Automated Changelog Generation

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for all tags and branches

      - name: Generate changelog entry
        run: |
          # Check if there are any tags
          if git rev-list --tags --max-count=1; then
            # Get the latest tag
            latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
            echo "Latest tag: $latest_tag"

            # Get commits since the latest tag
            commits=$(git log ${latest_tag}..HEAD --pretty=format:"- %s")
          else
            echo "No tags found. Using all commits."
            latest_tag="beginning"
            commits=$(git log --pretty=format:"- %s")
          fi

          if [ -z "$commits" ]; then
            echo "No new commits."
            exit 0
          fi

          # Prepare changelog content
          changelog_content="## Changes since $latest_tag\n\n$commits\n\n"

          # Update the changelog file
          echo "$changelog_content" | cat - CHANGELOG.md > temp && mv temp CHANGELOG.md

      - name: Commit and push changelog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog for $latest_tag"
          git push
